<?php

namespace AppBundle\Repository;

/**
 * membershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class membershipRepository extends \Doctrine\ORM\EntityRepository
{
}
