AppBundle\Entity\SRolModulo:
    type: entity
    table: s_rol_modulo
    indexes:
        IDX_BDCBE56690F1D76D:
            columns:
                - id_rol
        IDX_BDCBE566CAC67ADB:
            columns:
                - id_modulo
    id: {  }
    manyToOne:
        idRol:
            targetEntity: SRol
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rol:
                    referencedColumnName: id_rol
            orphanRemoval: false
        idModulo:
            targetEntity: SModulo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_modulo:
                    referencedColumnName: id_modulo
            orphanRemoval: false
    lifecycleCallbacks: {  }
